from data_options import DataOptions


class YahooAPIOption:

    def __init__(self, option, yahoo_option):
        self.option = option
        self.yahoo_option = yahoo_option

    def get_option(self):
        return self.option

    def get_yahoo_option(self):
        return self.yahoo_option


class YahooAPIOptions:
    ASK = YahooAPIOption(DataOptions.ASK, 'a')
    BID = YahooAPIOption(DataOptions.BID, 'b')
    ASK_REAL_TIME = YahooAPIOption(DataOptions.ASK_REAL_TIME, 'b2')
    BID_REAL_TIME = YahooAPIOption(DataOptions.BID_REAL_TIME, 'b3')
    PREVIOUS_CLOSE = YahooAPIOption(DataOptions.PREVIOUS_CLOSE, 'p')
    OPEN = YahooAPIOption(DataOptions.OPEN, 'o')
    DIVIDEND_YIELD = YahooAPIOption(DataOptions.DIVIDEND_YIELD, 'y')
    DIVIDEND_PER_SHARE = YahooAPIOption(DataOptions.DIVIDEND_PER_SHARE, 'd')
    DIVIDEND_PAY_DATE = YahooAPIOption(DataOptions.DIVIDEND_PAY_DATE, 'r1')
    EX_DIVIDEND_DATE = YahooAPIOption(DataOptions.EX_DIVIDEND_DATE, 'q')
    CHANGE = YahooAPIOption(DataOptions.CHANGE, 'c1')
    CHANGE_AND_PERCENT_CHANGE = YahooAPIOption(DataOptions.CHANGE_AND_PERCENT_CHANGE, 'c')
    CHANGE_REAL_TIME = YahooAPIOption(DataOptions.CHANGE_REAL_TIME, 'c6')
    CHANGE_PERCENT_REAL_TIME = YahooAPIOption(DataOptions.CHANGE_PERCENT_REAL_TIME, 'k2')
    CHANGE_IN_PERCENT = YahooAPIOption(DataOptions.CHANGE_IN_PERCENT, 'p2')
    LAST_TRADE_DATE = YahooAPIOption(DataOptions.LAST_TRADE_DATE, 'd1')
    TRADE_DATE = YahooAPIOption(DataOptions.TRADE_DATE, 'd2')
    LAST_TRADE_TIME = YahooAPIOption(DataOptions.LAST_TRADE_TIME, 't1')
    AFTER_HOURS_CHANGE_REAL_TIME = YahooAPIOption(DataOptions.AFTER_HOURS_CHANGE_REAL_TIME, 'c8')
    COMMISSION = YahooAPIOption(DataOptions.COMMISSION, 'c3')
    DAY_LOW = YahooAPIOption(DataOptions.DAY_LOW, 'g')
    DAY_HIGH = YahooAPIOption(DataOptions.DAY_HIGH, 'h')
    LAST_TRADE_WITH_TIME_REAL_TIME = YahooAPIOption(DataOptions.LAST_TRADE_WITH_TIME_REAL_TIME, 'k1')
    LAST_TRADE_WITH_TIME = YahooAPIOption(DataOptions.LAST_TRADE_WITH_TIME, 'l')
    LAST_TRADE_PRICE = YahooAPIOption(DataOptions.LAST_TRADE_PRICE, 'l1')
    ONE_YEAR_TARGET_PRICE = YahooAPIOption(DataOptions.ONE_YEAR_TARGET_PRICE, 't8')
    CHANGE_FROM_200_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.CHANGE_FROM_200_DAY_MOVING_AVERAGE, 'm5')
    PERCENT_CHANGE_FROM_200_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_200_DAY_MOVING_AVERAGE, 'm6')
    CHANGE_FROM_50_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.CHANGE_FROM_50_DAY_MOVING_AVERAGE, 'm7')
    PERCENT_CHANGE_FROM_50_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_50_DAY_MOVING_AVERAGE, 'm8')
    FIFTY_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.FIFTY_DAY_MOVING_AVERAGE, 'm3')
    TWO_HUNDRED_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.TWO_HUNDRED_DAY_MOVING_AVERAGE, 'm4')
    DAY_VALUE_CHANGE = YahooAPIOption(DataOptions.DAY_VALUE_CHANGE, 'w1')
    DAY_VALUE_CHANGE_REAL_TIME = YahooAPIOption(DataOptions.DAY_VALUE_CHANGE_REAL_TIME, 'w4')
    PRICE_PAID = YahooAPIOption(DataOptions.PRICE_PAID, 'p1')
    DAY_RANGE = YahooAPIOption(DataOptions.DAY_RANGE, 'm')
    DAY_RANGE_REAL_TIME = YahooAPIOption(DataOptions.DAY_RANGE_REAL_TIME, 'm2')
    HOLDINGS_GAIN_PERCENT = YahooAPIOption(DataOptions.HOLDINGS_GAIN_PERCENT, 'g1')
    ANNUALIZED_GAIN = YahooAPIOption(DataOptions.ANNUALIZED_GAIN, 'g3')
    HOLDINGS_GAIN = YahooAPIOption(DataOptions.HOLDINGS_GAIN, 'g4')
    HOLDINGS_GAIN_PERCENT_REAL_TIME = YahooAPIOption(DataOptions.HOLDINGS_GAIN_PERCENT_REAL_TIME, 'g5')
    HOLDINGS_GAIN_REAL_TIME = YahooAPIOption(DataOptions.HOLDINGS_GAIN_REAL_TIME, 'g6')
    FIFTY_TWO_WEEK_HIGH = YahooAPIOption(DataOptions.FIFTY_TWO_WEEK_HIGH, 'k')
    FIFTY_TWO_WEEK_LOW = YahooAPIOption(DataOptions.FIFTY_TWO_WEEK_LOW, 'j')
    CHANGE_FROM_FIFTY_TWO_WEEK_LOW = YahooAPIOption(DataOptions.CHANGE_FROM_FIFTY_TWO_WEEK_LOW, 'j5')
    CHANGE_FROM_FIFTY_TWO_WEEK_HIGH = YahooAPIOption(DataOptions.CHANGE_FROM_FIFTY_TWO_WEEK_HIGH, 'k4')
    PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_LOW = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_LOW, 'j6')
    PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_HIGH = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_HIGH, 'k5')
    FIFTY_TWO_WEEK_RANGE = YahooAPIOption(DataOptions.FIFTY_TWO_WEEK_RANGE, 'w')
    MORE_INFO = YahooAPIOption(DataOptions.MORE_INFO, 'i')
    MARKET_CAPITALIZATION = YahooAPIOption(DataOptions.MARKET_CAPITALIZATION, 'j1')
    MARKET_CAP_REAL_TIME = YahooAPIOption(DataOptions.MARKET_CAP_REAL_TIME, 'j3')
    FLOAT_SHARES = YahooAPIOption(DataOptions.FLOAT_SHARES, 'f6')
    NAME = YahooAPIOption(DataOptions.NAME, 'n')
    NOTES = YahooAPIOption(DataOptions.NOTES, 'n4')
    SYMBOL = YahooAPIOption(DataOptions.SYMBOL, 's')
    SHARES_OWNED = YahooAPIOption(DataOptions.SHARES_OWNED, 's1')
    STOCK_EXCHANGE = YahooAPIOption(DataOptions.STOCK_EXCHANGE, 'x')
    SHARES_OUTSTANDING = YahooAPIOption(DataOptions.SHARES_OUTSTANDING, 'j2')
    VOLUME = YahooAPIOption(DataOptions.VOLUME, 'v')
    ASK_SIZE = YahooAPIOption(DataOptions.ASK_SIZE, 'a5')
    BID_SIZE = YahooAPIOption(DataOptions.BID_SIZE, 'b6')
    LAST_TRADE_SIZE = YahooAPIOption(DataOptions.LAST_TRADE_SIZE, 'k3')
    AVERAGE_DAILY_VOLUME = YahooAPIOption(DataOptions.AVERAGE_DAILY_VOLUME, 'a2')
    TICKER_TREND = YahooAPIOption(DataOptions.TICKER_TREND, 't7')
    TRADE_LINKS = YahooAPIOption(DataOptions.TRADE_LINKS, 't6')
    ORDER_BOOK_REAL_TIME = YahooAPIOption(DataOptions.ORDER_BOOK_REAL_TIME, 'i5')
    HIGH_LIMIT = YahooAPIOption(DataOptions.HIGH_LIMIT, 'l2')
    LOW_LIMIT = YahooAPIOption(DataOptions.LOW_LIMIT, 'l3')
    HOLDINGS_VALUE = YahooAPIOption(DataOptions.HOLDINGS_VALUE, 'v1')
    HOLDINGS_VALUE_REAL_TIME = YahooAPIOption(DataOptions.HOLDINGS_VALUE_REAL_TIME, 'v7')
    REVENUE = YahooAPIOption(DataOptions.REVENUE, 's6')
    EARNINGS_PER_SHARE = YahooAPIOption(DataOptions.EARNINGS_PER_SHARE, 'e')
    EPS_ESTIMATE_CURRENT_YEAR = YahooAPIOption(DataOptions.EPS_ESTIMATE_CURRENT_YEAR, 'e7')
    EPS_ESTIMATE_NEXT_YEAR = YahooAPIOption(DataOptions.EPS_ESTIMATE_NEXT_YEAR, 'e8')
    EPS_ESTIMATE_NEXT_QUARTER = YahooAPIOption(DataOptions.EPS_ESTIMATE_NEXT_QUARTER, 'e9')
    BOOK_VALUE = YahooAPIOption(DataOptions.BOOK_VALUE, 'b4')
    EBITDA = YahooAPIOption(DataOptions.EBITDA, 'j4')
    PRICE_SALES = YahooAPIOption(DataOptions.PRICE_SALES, 'p5')
    PRICE_BOOK = YahooAPIOption(DataOptions.PRICE_BOOK, 'p6')
    P_E_RATIO = YahooAPIOption(DataOptions.P_E_RATIO, 'r')
    P_E_RATIO_REAL_TIME = YahooAPIOption(DataOptions.P_E_RATIO_REAL_TIME, 'r2')
    PEG_RATIO = YahooAPIOption(DataOptions.PEG_RATIO, 'r5')
    PRICE_EPS_ESTIMATE_CURRENT_YEAR = YahooAPIOption(DataOptions.PRICE_EPS_ESTIMATE_CURRENT_YEAR, 'r6')
    PRICE_EPS_ESTIMATE_NEXT_YEAR = YahooAPIOption(DataOptions.PRICE_EPS_ESTIMATE_NEXT_YEAR, 'r7')
    SHORT_RATIO = YahooAPIOption(DataOptions.SHORT_RATIO, 's7')