from data_options import DataOptions


class YahooAPIOption:

    def __init__(self, option, yahoo_option):
        self.option = option
        self.yahoo_option = yahoo_option

    def get_option(self):
        return self.option

    def get_yahoo_option(self):
        return self.yahoo_option


class YahooAPIOptions:
    ASK = YahooAPIOption(DataOptions.ASK, 'a')
    BID = YahooAPIOption(DataOptions.BID, 'b')
    ASK_REAL_TIME = YahooAPIOption(DataOptions.ASK_REAL_TIME, 'b2')
    BID_REAL_TIME = YahooAPIOption(DataOptions.BID_REAL_TIME, 'b3')
    PREVIOUS_CLOSE = YahooAPIOption(DataOptions.PREVIOUS_CLOSE, 'p')
    OPEN = YahooAPIOption(DataOptions.OPEN, 'o')
    DIVIDEND_YIELD = YahooAPIOption(DataOptions.DIVIDEND_YIELD, 'y')
    DIVIDEND_PER_SHARE = YahooAPIOption(DataOptions.DIVIDEND_PER_SHARE, 'd')
    DIVIDEND_PAY_DATE = YahooAPIOption(DataOptions.DIVIDEND_PAY_DATE, 'r1')
    EX_DIVIDEND_DATE = YahooAPIOption(DataOptions.EX_DIVIDEND_DATE, 'q')
    CHANGE = YahooAPIOption(DataOptions.CHANGE, '')
    CHANGE_AND_PERCENT_CHANGE = YahooAPIOption(DataOptions.CHANGE_AND_PERCENT_CHANGE, '')
    CHANGE_REAL_TIME = YahooAPIOption(DataOptions.CHANGE_REAL_TIME, '')
    CHANGE_PERCENT_REAL_TIME = YahooAPIOption(DataOptions.CHANGE_PERCENT_REAL_TIME, '')
    CHANGE_IN_PERCENT = YahooAPIOption(DataOptions.CHANGE_IN_PERCENT, '')
    LAST_TRADE_DATE = YahooAPIOption(DataOptions.LAST_TRADE_DATE, '')
    TRADE_DATE = YahooAPIOption(DataOptions.TRADE_DATE, '')
    LAST_TRADE_TIME = YahooAPIOption(DataOptions.LAST_TRADE_TIME, '')
    AFTER_HOURS_CHANGE_REAL_TIME = YahooAPIOption(DataOptions.AFTER_HOURS_CHANGE_REAL_TIME, '')
    COMMISSION = YahooAPIOption(DataOptions.COMMISSION, '')
    DAY_LOW = YahooAPIOption(DataOptions.DAY_LOW, '')
    DAY_HIGH = YahooAPIOption(DataOptions.DAY_HIGH, '')
    LAST_TRADE_WITH_TIME_REAL_TIME = YahooAPIOption(DataOptions.LAST_TRADE_WITH_TIME_REAL_TIME, '')
    LAST_TRADE_WITH_TIME = YahooAPIOption(DataOptions.LAST_TRADE_WITH_TIME, '')
    LAST_TRADE_PRICE = YahooAPIOption(DataOptions.LAST_TRADE_PRICE, 'l1')
    ONE_YEAR_TARGET_PRICE = YahooAPIOption(DataOptions.ONE_YEAR_TARGET_PRICE, '')
    CHANGE_FROM_200_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.CHANGE_FROM_200_DAY_MOVING_AVERAGE, '')
    PERCENT_CHANGE_FROM_200_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_200_DAY_MOVING_AVERAGE, '')
    CHANGE_FROM_50_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.CHANGE_FROM_50_DAY_MOVING_AVERAGE, '')
    PERCENT_CHANGE_FROM_50_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_50_DAY_MOVING_AVERAGE, '')
    FIFTY_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.FIFTY_DAY_MOVING_AVERAGE, '')
    TWO_HUNDRED_DAY_MOVING_AVERAGE = YahooAPIOption(DataOptions.TWO_HUNDRED_DAY_MOVING_AVERAGE, '')
    DAY_VALUE_CHANGE = YahooAPIOption(DataOptions.DAY_VALUE_CHANGE, '')
    DAY_VALUE_CHANGE_REAL_TIME = YahooAPIOption(DataOptions.DAY_VALUE_CHANGE_REAL_TIME, '')
    PRICE_PAID = YahooAPIOption(DataOptions.PRICE_PAID, '')
    DAY_RANGE = YahooAPIOption(DataOptions.DAY_RANGE, '')
    DAY_RANGE_REAL_TIME = YahooAPIOption(DataOptions.DAY_RANGE_REAL_TIME, '')
    HOLDINGS_GAIN_PERCENT = YahooAPIOption(DataOptions.HOLDINGS_GAIN_PERCENT, '')
    ANNUALIZED_GAIN = YahooAPIOption(DataOptions.ANNUALIZED_GAIN, '')
    HOLDINGS_GAIN = YahooAPIOption(DataOptions.HOLDINGS_GAIN, '')
    HOLDINGS_GAIN_PERCENT_REAL_TIME = YahooAPIOption(DataOptions.HOLDINGS_GAIN_PERCENT_REAL_TIME, '')
    HOLDINGS_GAIN_REAL_TIME = YahooAPIOption(DataOptions.HOLDINGS_GAIN_REAL_TIME, '')
    FIFTY_TWO_WEEK_HIGH = YahooAPIOption(DataOptions.FIFTY_TWO_WEEK_HIGH, '')
    FIFTY_TWO_WEEK_LOW = YahooAPIOption(DataOptions.FIFTY_TWO_WEEK_LOW, '')
    CHANGE_FROM_FIFTY_TWO_WEEK_LOW = YahooAPIOption(DataOptions.CHANGE_FROM_FIFTY_TWO_WEEK_LOW, '')
    CHANGE_FROM_FIFTY_TWO_WEEK_HIGH = YahooAPIOption(DataOptions.CHANGE_FROM_FIFTY_TWO_WEEK_HIGH, '')
    PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_LOW = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_LOW, '')
    PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_HIGH = YahooAPIOption(DataOptions.PERCENT_CHANGE_FROM_FIFTY_TWO_WEEK_HIGH, '')
    FIFTY_TWO_WEEK_RANGE = YahooAPIOption(DataOptions.FIFTY_TWO_WEEK_RANGE, '')
    MORE_INFO = YahooAPIOption(DataOptions.MORE_INFO, '')
    MARKET_CAPITALIZATION = YahooAPIOption(DataOptions.MARKET_CAPITALIZATION, '')
    MARKET_CAP_REAL_TIME = YahooAPIOption(DataOptions.MARKET_CAP_REAL_TIME, '')
    FLOAT_SHARES = YahooAPIOption(DataOptions.FLOAT_SHARES, '')
    NAME = YahooAPIOption(DataOptions.NAME, '')
    NOTES = YahooAPIOption(DataOptions.NOTES, '')
    SYMBOL = YahooAPIOption(DataOptions.SYMBOL, '')
    SHARES_OWNED = YahooAPIOption(DataOptions.SHARES_OWNED, '')
    STOCK_EXCHANGE = YahooAPIOption(DataOptions.STOCK_EXCHANGE, '')
    SHARES_OUTSTANDING = YahooAPIOption(DataOptions.SHARES_OUTSTANDING, '')
    VOLUME = YahooAPIOption(DataOptions.VOLUME, '')
    ASK_SIZE = YahooAPIOption(DataOptions.ASK_SIZE, '')
    BID_SIZE = YahooAPIOption(DataOptions.BID_SIZE, '')
    LAST_TRADE_SIZE = YahooAPIOption(DataOptions.LAST_TRADE_SIZE, '')
    AVERAGE_DAILY_VOLUME = YahooAPIOption(DataOptions.AVERAGE_DAILY_VOLUME, '')
    TICKER_TREND = YahooAPIOption(DataOptions.TICKER_TREND, '')
    TRADE_LINKS = YahooAPIOption(DataOptions.TRADE_LINKS, '')
    ORDER_BOOK_REAL_TIME = YahooAPIOption(DataOptions.ORDER_BOOK_REAL_TIME, '')
    HIGH_LIMIT = YahooAPIOption(DataOptions.HIGH_LIMIT, '')
    LOW_LIMIT = YahooAPIOption(DataOptions.LOW_LIMIT, '')
    HOLDINGS_VALUE = YahooAPIOption(DataOptions.HOLDINGS_VALUE, '')
    HOLDINGS_VALUE_REAL_TIME = YahooAPIOption(DataOptions.HOLDINGS_VALUE_REAL_TIME, '')
    REVENUE = YahooAPIOption(DataOptions.REVENUE, '')
    EARNINGS_PER_SHARE = YahooAPIOption(DataOptions.EARNINGS_PER_SHARE, '')
    EPS_ESTIMATE_CURRENT_YEAR = YahooAPIOption(DataOptions.EPS_ESTIMATE_CURRENT_YEAR, '')
    EPS_ESTIMATE_NEXT_YEAR = YahooAPIOption(DataOptions.EPS_ESTIMATE_NEXT_YEAR, '')
    EPS_ESTIMATE_NEXT_QUARTER = YahooAPIOption(DataOptions.EPS_ESTIMATE_NEXT_QUARTER, '')
    BOOK_VALUE = YahooAPIOption(DataOptions.BOOK_VALUE, '')
    EBITDA = YahooAPIOption(DataOptions.EBITDA, '')
    PRICE_SALES = YahooAPIOption(DataOptions.PRICE_SALES, '')
    PRICE_BOOK = YahooAPIOption(DataOptions.PRICE_BOOK, '')
    P_E_RATIO = YahooAPIOption(DataOptions.P_E_RATIO, '')
    P_E_RATIO_REAL_TIME = YahooAPIOption(DataOptions.P_E_RATIO_REAL_TIME, '')
    PEG_RATIO = YahooAPIOption(DataOptions.PEG_RATIO, '')
    PRICE_EPS_ESTIMATE_CURRENT_YEAR = YahooAPIOption(DataOptions.PRICE_EPS_ESTIMATE_CURRENT_YEAR, '')
    PRICE_EPS_ESTIMATE_NEXT_YEAR = YahooAPIOption(DataOptions.PRICE_EPS_ESTIMATE_NEXT_YEAR, '')
    SHORT_RATIO = YahooAPIOption(DataOptions.SHORT_RATIO, '')